POST http://127.0.0.1:8000/api/auth/register
Content-Type: application/json

{
    "name": "Bariq Firjatullah",
    "email": "bariq21@gmail.com",
    "password": "bariq123123"
}

###

POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{}

###
POST http://127.0.0.1:8000/api/role
Content-Type: application/json

{
    "name": "admin"
}

###
### GET request to example server
GET http://127.0.0.1:8000/api/role

###


